### ISSUE TITLE
Errors when running Sprout interactively

### ISSUE THREAD

**Issue by eleanor-merry** [Metaswitch/sprout#1128]
Running Sprout interactively generates a lot of errors, e.g.:

```
ubuntu@ip-10-0-0-152:~/sprout$ LD_LIBRARY_PATH=usr/lib:$LD_LIBRARY_PATH build/bin/sprout -t --domain=domain --scscf=5054 --scscf-uri="sip:cluster:5054;transport=TCP" --hss=cluster --log-file=/var/log/sprout --log-level=2
Log directory set to /var/log/sprout
Log level set to 2
MIB search path: /home/ubuntu/.snmp/mibs:/usr/share/snmp/mibs:/usr/share/snmp/mibs/iana:/usr/share/snmp/mibs/ietf:/usr/share/mibs/site:/usr/share/snmp/mibs:/usr/share/mibs/iana:/usr/share/mibs/ietf:/usr/share/mibs/netsnmp
Cannot find module (SNMPv2-TC): At line 10 in /usr/share/snmp/mibs/UCD-DLMOD-MIB.txt
Cannot find module (SNMPv2-SMI): At line 34 in /usr/share/snmp/mibs/UCD-SNMP-MIB.txt
Cannot find module (SNMPv2-TC): At line 37 in /usr/share/snmp/mibs/UCD-SNMP-MIB.txt
Did not find 'enterprises' in module #-1 (/usr/share/snmp/mibs/UCD-SNMP-MIB.txt)
Did not find 'DisplayString' in module #-1 (/usr/share/snmp/mibs/UCD-SNMP-MIB.txt)
Did not find 'TruthValue' in module #-1 (/usr/share/snmp/mibs/UCD-SNMP-MIB.txt)
Unlinked OID in UCD-SNMP-MIB: ucdavis ::= { enterprises 2021 }
Undefined identifier: enterprises near line 39 of /usr/share/snmp/mibs/UCD-SNMP-MIB.txt
Did not find 'DisplayString' in module #-1 (/usr/share/snmp/mibs/UCD-DLMOD-MIB.txt)
Did not find 'ucdExperimental' in module UCD-SNMP-MIB (/usr/share/snmp/mibs/UCD-DLMOD-MIB.txt)
...
```

**Comment by rkd-msw** [comment]
I can't reproduce this with https://github.com/Metaswitch/cpp-common/pull/326 - can you retest now that i've merged that?

**Comment by eleanor-merry** [comment]
I still see one error in the logs:
10-07-2015 15:23:55.366 UTC Warning (Net-SNMP): Warning: Failed to connect to the agentx master agent ([NIL]):
You're going to update the dev docs (https://github.com/Metaswitch/sprout/blob/dev/docs/Development.md#running-sprout-locally) to cover this
